# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - wa-fmc-turnos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies
        run: dotnet restore src/GestionTurnos.Presentation/GestionTurnos.Presentation.csproj

      - name: Build application
        run: dotnet build src/GestionTurnos.Presentation/GestionTurnos.Presentation.csproj --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish src/GestionTurnos.Presentation/GestionTurnos.Presentation.csproj -c Release -o myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies
        run: dotnet restore src/GestionTurnos.Presentation/GestionTurnos.Presentation.csproj

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_533536A8F1E74A9F919DEEFA84590CC3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FD333AEC637545FDB7FCB127E3BC503E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AEE2626FD080409ABAC18D49351FFAD5 }}

      - name: Set DB Connection string in Azure Web App settings
        run: az webapp config appsettings set --resource-group "fmc_turnos" --name "wa-fmc-turnos" --settings 'ConnectionStrings__DBConnectionString=${{ secrets.DBCONNECTIONSTRING }}'
       
      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef --version 10.*

      - name: Update database with EF Core migrations
        run: dotnet ef database update --project src/GestionTurnos.Infrastructure/GestionTurnos.Infrastructure.csproj --startup-project src/GestionTurnos.Presentation/GestionTurnos.Presentation.csproj
        env:
            ASPNETCORE_ENVIRONMENT: Production
            ConnectionStrings__DBConnectionString: ${{ secrets.DBCONNECTIONSTRING }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'wa-fmc-turnos'
          slot-name: 'Production'
          package: .